### ISSUE TITLE
'TNT' option update

### ISSUE THREAD

**Issue by AllYourBlocks** [AllYourBlocks/ChunkWars#103]
TNT mode to be renamed to 'Armageddon' in code and on the sign

Each Player to get a stack of 64 TNT in their inventory at the point they are teleported to the team houses in the arena

**Comment by AllYourBlocks** [comment]
Working as intended, thanks!

**Comment by AllYourBlocks** [comment]
@slipcor Let's also give each player a Flint and Steel

**Comment by slipcor** [comment]
such a generous mapmaker!

**Comment by AllYourBlocks** [comment]
Tested and working

**Comment by AllYourBlocks** [comment]
"Armageddon" mode to be renamed to "TNT" for naming consistency with other Options
