### ISSUE TITLE
Potions option update

### ISSUE THREAD

**Issue by AllYourBlocks** [AllYourBlocks/ChunkWars#104]
Each player should get a set of potions at the point they are teleported to the team houses in the arena, as follows;

1 Fire Resistance (3:00)
1 Invisibility (3:00)
1 Swiftness  Speed II (1:30)
1 Regeneration - Regeneration II (0:22)
1 Strength - Strength II (1:30)
1 Leaping - Jump Boost II (1:30)
1 Night Vision (3:00)
1 Water Breathing (3:00)
1 Slow Falling (1:30)

1 Splash - Slowness (1:30)
1 Splash - Weakness (1:30)
1 Splash - Poison II (0:21)
1 Splash - Instant Damage II

**Comment by AllYourBlocks** [comment]
![2022-04-06_00 30 13](https://user-images.githubusercontent.com/85025007/161867455-86371fff-c314-4f8d-995e-78685a2295a2.png)

**Comment by AllYourBlocks** [comment]
@slipcor Is it possible to populate the 'extended'(?) Inventory first, so that items appear first in these slots...?

![2022-05-07_14 30 42](https://user-images.githubusercontent.com/85025007/167256670-294fca00-b182-4874-b670-2641415b8bf0.png)

**Comment by slipcor** [comment]
Technically it is possible, yes, do you mean for every option or just this? It might become tricky when we have multiple options and these slots might be in use. I can not "get the first unused slot", I have to specificy a slot number, so.... only way to do this is FIRST give THESE items into the specific slots and then continue on from there....

**Comment by AllYourBlocks** [comment]
I meant as a general 'is it a thing that can be done and how'

Thanks for the info, I think, given the likely difficulties we would run into with multiple options, that we leave the behaviour as it curently is. Thanks!
