### ISSUE TITLE
Nether did not correctly pre-spawn in 2-Team Modern Arena when Option was turned on

### ISSUE THREAD

**Issue by AllYourBlocks** [AllYourBlocks/ChunkWars#120]
Similar to bug we had with Condensed?

**Comment by AllYourBlocks** [comment]
Same as #118 ?!

**Comment by slipcor** [comment]
Yes I am fairly sure this was fixed back then, broken when adding the randomness and now fixed again :)

**Comment by AllYourBlocks** [comment]
Thanks, will test

**Comment by AllYourBlocks** [comment]
Tested and working in new Arena generation code
