### ISSUE TITLE
Add Adventure Mode to Options Panel and Options

### ISSUE THREAD

**Issue by AllYourBlocks** [AllYourBlocks/ChunkWars#124]

**Comment by AllYourBlocks** [comment]
Added to Options Panel

**Comment by AllYourBlocks** [comment]
Adventure Mode works, but not as I intended it to.

Mojang changed the way Adventure Mode works (ages ago apparently) and it no longer 'auto allows' blocks to be broken by the correct tool for them.

@slipcor Do you know if there is a way to do this en-masse for all blocks (some kind of toggle?), or do we have to add every block individually to every type of tool?

**Comment by slipcor** [comment]
I have no idea how this even works, I will look into it

**Comment by slipcor** [comment]
```In [1.8](https://minecraft-archive.fandom.com/wiki/1.8_-_The_Bountiful_Update), adventure mode was made even harder; players couldn't break any blocks with any tool anymore, and they couldn't place them either. What players would have to do now is put an NBT tag on a certain block in order for it to be placed on anything (for example, a button with a "Can be placed on NBT tag", can only be placed on that or these blocks), so a player can't place the block on [Stone](https://minecraft-archive.fandom.com/wiki/Stone) if its NBT tag was dirt. For tools ([Axe](https://minecraft-archive.fandom.com/wiki/Axe), [Pickaxe](https://minecraft-archive.fandom.com/wiki/Pickaxe), etc.) there's a "Can Break" NBT tag, which allows a player to do anything with that block's breaking purpose (A sword with the "Can Break" tag for [Netherrack](https://minecraft-archive.fandom.com/wiki/Netherrack) will allow the sword to break Netherrack).```

So we need to add nbt tags to certain ITEMS and these items can then be used as proper tools --- every player needs to be given a set of these items then... so players never can CRAFT an item that works this way? well... we can spam update players items in hand :)

**Comment by slipcor** [comment]
oh well yes we have to add one NBT tag for every block we want to allow. how developer friendly xD

**Comment by AllYourBlocks** [comment]
Yeh, we're not doing that amount of work - unless there's some kind of plugin that could write the code for us, or generate whatever we need, in such a way that it works how 'original' Adventure Mode worked - and could be kept up to date easily for future versions of Minecraft.

I think I understand Mojang's perspective and the incentive behind creating a gamemode that's useful and fully customisable for mapmakers, but it feels very short-sighted not to include both an 'Adventure Mode' and a 'Mapmaker Mode'.

@slipcor Is there some way of pulling existing data out of the game and then auto-generating code which would result in 'expected behaviour' for every tool and every block in the game, both current and future?

**Comment by slipcor** [comment]
potentially. if I recall correctly, blocks do have tags, like "#wools" or something, I have seen "#axe-breakable" or similar, so if these exist we can do a reverse thing here and look for all the blocks that have this tag and reverse engineer tags to give to the items.

**Comment by AllYourBlocks** [comment]
Ok. This is low priority for now, let's revisit in the future and see how much work would be involved before spending time on it.

**Comment by AllYourBlocks** [comment]
Discussed and removing this game mode
