### ISSUE TITLE
Add existing breakout function to the Start Team Selection button, so that it becomes Start / Stop for all players

### ISSUE THREAD

**Issue by AllYourBlocks** [AllYourBlocks/ChunkWars#20]
Make sure we remove the current 'delete button on pressing' function.

**Comment by AllYourBlocks** [comment]
Bugged, needs fix

**Comment by AllYourBlocks** [comment]
Bugged, needs fix

**Comment by ffaen** [comment]
If we can run a closed test with 4 players to verify that the commit 94e87f4 fixes the issue we can re-close

**Comment by AllYourBlocks** [comment]
Checked and bug is fixed
