### ISSUE TITLE
Suggestion: Shop

### ISSUE THREAD

**Issue by PrimePenguins** [AllYourBlocks/ChunkWars#24]
It will be able to give you items. such as, 2 Emerlads for arrows.

**Comment by AllYourBlocks** [comment]
This is an interesting suggestion, but I won't be adding a specific shop to the game. I don't think it's a good fit with one of the fundamental concepts of the map - to be as-vanilla-as-possible.

It's worth noting that this kind of 'shop' functionality already exists via Villagers, and is already in the map. In the future, I plan to add specific trades to each of the Villagers, so players will be able to take advantage of that 'shopping' function. There are already lots of Emeralds in the map for when I get to that point.
