### ISSUE TITLE
Consider adding ‘Pick a Random Player’ button to the Team Selection System

### ISSUE THREAD

**Issue by AllYourBlocks** [AllYourBlocks/ChunkWars#26]
Would want two(?) 1 per Captain.

These could be *in* the Captains' exclusion zones adjacent to the general Player Selection area.

**Comment by AllYourBlocks** [comment]
Signpost and button added

**Comment by ffaen** [comment]
> Signpost and button added

Can you provide coords or a new map in dropbox for specifying button locations

**Comment by AllYourBlocks** [comment]
Done
