### ISSUE TITLE
Endgame balancing

### ISSUE THREAD

**Issue by slipcor** [AllYourBlocks/ChunkWars#43]
As soon as one team loses their bed, since keepInventory is on, the game sort of becomes really hard to a degree that is basically is over, and as soon as someone is in the house and breaking the bed, enganging that person really does not make any sense any more. Here are some ideas that I had while you were talking about this on stream:

As soon as an enemy bed is picked up

- turn keepInventory off
- start some sort of adverse effect on the defending / "winning" team, so they do not spawn camp their bed but have to move out
  - hunger
  - fatigue
  - slowness
  - weakness

Obivously there needs to be a way to undo this as soon as a team places their own bed down again :)

**Comment by AllYourBlocks** [comment]
Some cool ideas here that could be useful for other maps, but after consideration I don't think this fits well with the fundamental concept of this map.
