### ISSUE TITLE
Consider disabling health regeneration during the sumo fight

### ISSUE THREAD

**Issue by ffaen** [AllYourBlocks/ChunkWars#46]
This is prevent longer games where players are not falling off the chunks, since you never need food and so you end up regenerating any hits you take

**Comment by AllYourBlocks** [comment]
I want to run lots of sumo tests to help with decision

**Comment by slipcor** [comment]
To disable weakness, we can give players the tag "Ingame"

**Comment by AllYourBlocks** [comment]
After testing and reflection, I think the existing Sumo version is better reflective of expected gameplay during Chunk Wars matches, and therefore we should stick with Vanilla behaviours.
