### ISSUE TITLE
Clarity issue with Detry-Sign solution

### ISSUE THREAD

**Issue by slipcor** [AllYourBlocks/ChunkWars#55]
If we go for the solution as-is, it could be either hard to see [from the lobby] which options are on/selected unless we do not lock the "to options panel area" as it is right now, it is possible to see all options values from the lobby from a distance, this visual clarity would be good to keep

**Comment by ffaen** [comment]
Relates to #54

**Comment by AllYourBlocks** [comment]
Resolved. #54 closed too.
