### ISSUE TITLE
Ocean Waterstop does not work

### ISSUE THREAD

**Issue by slipcor** [AllYourBlocks/ChunkWars#59]
@ffaen was there some prerequisite for the chunks we have to do? Something block-related?

We basically set everything up, your ocean worked, blocks' ocean did not :O

**Comment by ffaen** [comment]
With waterstop enabled, surround the chunk with a solid block and then do a fill command, replacing that solid block with ‘cave_air’

Then save the chunk

**Comment by slipcor** [comment]
alright. I had a test run that did the trick. will you be around today to talk?
