### ISSUE TITLE
Investigate and develop system for resetting the Arenas, and Lobby Sumo after each game or Team Selection, by using Structure Blocks

### ISSUE THREAD

**Issue by AllYourBlocks** [AllYourBlocks/ChunkWars#6]
This is currently on hold. It is not possible to regenerate the Arena with Structure Blocks without the water in the Ocean Chunk updating and flowing out of the Arena.

**Comment by ffaen** [comment]
Thanks to some new information, this should now be at least partially possible. We're trying to use cave_air to allow the restoring of the world without water flowing, and then resetting the functionality of cave air to act like normal air during gameplay
