### ISSUE TITLE
When the Ocean Chunk is loaded in, the 'front' Chest in the Shipwreck gets  waterlogged from the front stair

### ISSUE THREAD

**Issue by AllYourBlocks** [AllYourBlocks/ChunkWars#73]

**Comment by AllYourBlocks** [comment]
- Could fix by replacing stairs around the Shipwreck with full blocks, but this is less 'as close to vanilla as possible'

- Could fix by overwriting the space after it's generated, and then putting the Chest back in with resources

- Other solutions?!

**Comment by AllYourBlocks** [comment]
This didn't appear to happen when we tested on 1.18.1
Needs further tests on 1.18.1 and 1.18.2 to check

**Comment by slipcor** [comment]
It did not happen on my (paper!) 1.18.2 server yesterday. Could it be related to the RAM issue we had on the server?

**Comment by AllYourBlocks** [comment]
Yep, fairly sure this was a Minecraft bug, which has been fixed upstream
