### ISSUE TITLE
Green team name and green text color are mismatched

### ISSUE THREAD

**Issue by slipcor** [AllYourBlocks/ChunkWars#75]
A) Team colors are limited to the named colors that minecraft gives us, **green** (lime, curently the color of the team for the "players to select") and **dark_green** (currently used as "Team Green" color), Neither are really close to the sign color.
B) The text color is based on the center color used by a glow squid ink lime colored font, specifically it is 'bdfc00'

We need a decision which color to use where, we could change the sign colors to be the lime (green) text color, but I have a feeling it will look sub-optimal

**Comment by slipcor** [comment]
Chat color: "lime", sign color stays "glow lime"

**Comment by AllYourBlocks** [comment]
We've fixed this, issue is due to limitations in Minecraft, due to Mojang's inconsistencies with the use of colours in chat, scoreboards, team names, on signs, etc. Current solution is 'best case' for now unless they change things.
