### ISSUE TITLE
Respawn = false -> break the beds

### ISSUE THREAD

**Issue by slipcor** [AllYourBlocks/ChunkWars#87]

**Comment by AllYourBlocks** [comment]
Respawn Option should /fill or /setblock the 4 (2 teams) or 8 (4 teams) relevant bed blocks with Air

**Comment by AllYourBlocks** [comment]
Beds are breaking correctly and not dropping items.

However, beds are breaking after countdown at the start of game, at the same moment as the barrier blocks are removed from the doorways.

I think it makes more sense for the beds instead to be removed as soon as players arrive in their arena houses.

**Comment by AllYourBlocks** [comment]
Working as intended with that adjustment, thanks!
