### ISSUE TITLE
Command to break out of the game

### ISSUE THREAD

**Issue by slipcor** [AllYourBlocks/ChunkWars#90]
To blocks, what exactly should this command do? Reset chunks? teleport to lobby? both? anything else? options?

**Comment by AllYourBlocks** [comment]
End the game, put everyone in spectator and leave them above the arena, and trigger the 'game has ended' state where the Reset and Restart clickable triggers are in the chatbox

**Comment by AllYourBlocks** [comment]
@slipcor - Is this now /function breakout:game after the command syntax was changed?!

**Comment by slipcor** [comment]
@AllYourBlocks yes, exactly :)

**Comment by AllYourBlocks** [comment]
Tested and working, thanks!
